all: LinkedList_Generic.o Graph_Generic.o main.o
	gcc LinkedList_Generic.o Graph_Generic.o main.o -o hello
LinkedList_Generic.o: LinkedList_Generic.c
	gcc -c LinkedList_Generic.c
Graph_Generic.o: Graph_Generic.c
	gcc -c Graph_Generic.c
main.o: main.c
	gcc -c main.c
